---
    version: "2.1"
    services:
      wireguard:
        image: linuxserver/wireguard:arm64v8-latest
        container_name: wireguard
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Los_Angeles
          - SERVERPORT=51820
          - PEERS=1
          - PEERDNS=auto
        volumes:
          - /path/to/appdata/config:/config
          - /lib/modules:/lib/modules
        ports:
          - 51820:51820/udp
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped